Initial Russian translation
opendata-stuttgart/sensor.community pull request #59
Opened 2020-05-04 15:17 UTC by DeeKey

Please note, that I have added a direct link to assembly in Russian how to buy and assemble  the sensor. It is maintained by me in GoogleDocs. 
    "docs": "<a href=\"shorturl.at/TY014\"></a>",

2020-05-11 18:19 UTC, ohheyitsdave requested changes
Thanks @DeeKey for your contribution 😊 
Just two little errors, then I can merge it to develop branch.

2020-05-11 18:19 UTC, ohheyitsdave commented on src/components/LanguageSwitcher.svelte
> +           class:selected="{lang === 'ru' ? 'selected' : ''}"> {flag('ru')} sk</a>
you forgot to change `sk` to `ru`.

2020-05-11 18:19 UTC, ohheyitsdave commented on src/utils/initI18n.js
> +import sk from '../../locales/ru';
like in the other comment `sk`to `ru`

2020-05-13 09:37 UTC, DeeKey commented
Thank you for your attention!
Over time there will definitely be more. Hard to commit everything in one time without making any mistake  (((
Do you need any input from me, or you will fix everything yourself?

2020-05-14 18:49 UTC, ohheyitsdave approved these changes
hope this works fixing the issues inside Github.

2020-05-14 19:15 UTC, merged

2020-05-14 19:23 UTC, ohheyitsdave commented
Works 🙌 Thanks again for your help!